# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ff95b2b4d7bddeae09432409188001a043d94654bd41dbf0e4887087c31c8467234294258ba55b22d9f62f9d4382bf6864d5666f72ae74e14a4a85b33c3d712

test:
  secret_key_base: 5f7b107add56d4dba94b4bb1caa01eb05cf58f14a7485209dccc0111977d73ca379b4ad49b9229a5b23aa69e87a2e13688133d289ffcc8008b487fcdfe6e55c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
